export interface Supermarket {
  id: string;
  name: string;
  color: string;
  volantino: string; // Link diretto al volantino online
  location?: string; // Località specifica se necessario
}

export const SUPERMARKETS: Supermarket[] = [
  {
    id: 'lidl',
    name: 'Lidl',
    color: '#0050AA',
    volantino: 'https://www.lidl.it/c/volantino-lidl/s10018048?ar=70100',
  },
  {
    id: 'md',
    name: 'MD',
    color: '#FFD700',
    volantino: 'https://www.mdspa.it/punti-vendita/Sicilia/AG-Agrigento/516-FAVARA',
    location: 'Favara (AG)',
  },
  {
    id: 'ilgigante',
    name: 'Il Gigante',
    color: '#E30613',
    volantino: 'https://ilgigante.net/cerca-punto-vendita/risultato-ricerca-punti-vendita/scheda-punto-vendita/?punto=5',
  },
  {
    id: 'unes',
    name: 'Unes',
    color: '#FF6B35',
    volantino: 'https://www.unes.it/volantino/',
  },
  {
    id: 'crai',
    name: 'Crai',
    color: '#E31E24',
    volantino: 'https://www.crai-supermercati.it/volantino/crai-simpatia-cluster-5-88/?pdv=6191',
  },
  {
    id: 'despar',
    name: 'Despar',
    color: '#009640',
    volantino: 'https://www.despar.it/it/punto-vendita-despar/776/bologna',
    location: 'Bologna',
  },
  {
    id: 'prestofresco',
    name: 'Presto Fresco',
    color: '#FF6B00',
    volantino: 'https://prestofresco.it/punto-vendita/nichelino-via-martiri-30/VmlhIE1hcnRpcmksIDMwTklDSEVMSU5P/#store',
    location: 'Nichelino',
  },
  {
    id: 'centesimo',
    name: 'Il Centesimo',
    color: '#0066CC',
    volantino: 'https://www.ilcentesimo.com/volantino-offerte',
  },
  {
    id: 'eurospin',
    name: 'Eurospin',
    color: '#E30613',
    volantino: 'https://www.eurospin.it/volantino-store-eurospin/?codice_pv=540690',
  },
  {
    id: 'tigros',
    name: 'Tigros',
    color: '#FF6B00',
    volantino: 'https://www.tigros.it/volantini/',
  },
  {
    id: 'iper',
    name: 'Iper',
    color: '#E30613',
    volantino: 'https://volantini.iper.it/punti-vendita/iper-savignano-sul-rubicone',
    location: 'Savignano sul Rubicone',
  },
  {
    id: 'mercatolocal',
    name: 'Mercato Local',
    color: '#009640',
    volantino: 'https://www.mymercato.it/punti-vendita/piemonte/mercat--local---santo-stefano-belbo/offerte-volantino',
    location: 'Santo Stefano Belbo',
  },
  {
    id: 'mercatoextra',
    name: 'Mercato Extra',
    color: '#0066CC',
    volantino: 'https://www.mymercato.it/punti-vendita/piemonte/mercato-extra-alessandria---via-vecchia-torino/offerte-volantino',
    location: 'Alessandria',
  },
  {
    id: 'mercatobig',
    name: 'Mercato Big',
    color: '#E30613',
    volantino: 'https://www.mymercato.it/punti-vendita/piemonte/mercato-big-bra/offerte-volantino',
    location: 'Bra',
  },
  {
    id: 'bennet',
    name: 'Bennet',
    color: '#0066CC',
    volantino: 'https://www.bennet.com/flyer?s=0150',
  },
  {
    id: 'esselunga',
    name: 'Esselunga',
    color: '#E30613',
    volantino: 'https://www.esselunga.it/it-it/promozioni/volantini.esselunga-di-alessandria.ale.html',
    location: 'Alessandria',
  },
  {
    id: 'naturasi',
    name: 'NaturaSì',
    color: '#009640',
    volantino: 'https://www.naturasi.it/offerte',
  },
  {
    id: 'ins',
    name: 'INS',
    color: '#FF6B35',
    volantino: 'https://www.insmercato.it/volantino/',
  },
  {
    id: 'ilgigante2',
    name: 'Il Gigante (Punto 56)',
    color: '#E30613',
    volantino: 'https://ilgigante.net/cerca-punto-vendita/risultato-ricerca-punti-vendita/scheda-punto-vendita/?punto=56',
  },
  {
    id: 'famila',
    name: 'Famila',
    color: '#0066CC',
    volantino: 'https://www.famila.it/punti-vendita/lombardia/famila-robbio/offerte-volantino',
    location: 'Robbio',
  },
  {
    id: 'familasuperstore',
    name: 'Famila Superstore',
    color: '#0066CC',
    volantino: 'https://www.famila.it/punti-vendita/lombardia/famila-superstore-crema-via-caponetto/offerte-volantino',
    location: 'Crema',
  },
  {
    id: 'familamarket',
    name: 'Famila Market',
    color: '#0066CC',
    volantino: 'https://www.famila.it/punti-vendita/piemonte/famila-market-ivrea/offerte-volantino',
    location: 'Ivrea',
  },
  {
    id: 'gulliver',
    name: 'Gulliver',
    color: '#FF6B00',
    volantino: 'https://www.supergulliver.it/punti-vendita/emilia-romagna/gulliver-piu-piacenza-via-rio-farnese--14-a/offerte-volantino',
    location: 'Piacenza',
  },
  {
    id: 'decomarket',
    name: 'Deco Market',
    color: '#E30613',
    volantino: 'https://puntivenditadeco.multicedi.it/it/italia/napoli/napoli-via-andrea-cantelmo',
    location: 'Napoli - Via Cantelmo',
  },
  {
    id: 'decosupermercati',
    name: 'Deco Supermercati',
    color: '#E30613',
    volantino: 'https://puntivenditadeco.multicedi.it/it/italia/napoli/napoli-via-enrico-cosenz',
    location: 'Napoli - Via Cosenz',
  },
  {
    id: 'paghipoco',
    name: 'Paghi Poco',
    color: '#FFD700',
    volantino: 'https://paghipoco.com/volantino-e-offerte/',
  },
  {
    id: 'todis',
    name: 'Todis',
    color: '#E30613',
    volantino: 'https://www.todis.it/promozioni/volantino/umbria/standard',
    location: 'Umbria',
  },
  {
    id: 'eurospar',
    name: 'Eurospar',
    color: '#009640',
    volantino: 'https://www.despar.it/it/punto-vendita-eurospar/900/lugo-di-romagna',
    location: 'Lugo di Romagna',
  },
  {
    id: 'interspar',
    name: 'Interspar',
    color: '#009640',
    volantino: 'https://www.despar.it/it/punto-vendita-interspar/1001/castelfranco-veneto',
    location: 'Castelfranco Veneto',
  },
  {
    id: 'penny',
    name: 'Penny',
    color: '#E30613',
    volantino: 'https://www.penny.it/sfoglia-il-volantino-mobile',
  },
  {
    id: 'conad',
    name: 'Conad',
    color: '#ED1C24',
    volantino: 'https://volantini.coopgrupporadenza.it/',
  },
  {
    id: 'pampanorama1',
    name: 'Pam Panorama Milano',
    color: '#0066CC',
    volantino: 'https://www.pampanorama.it/punti-vendita/milano-olona',
    location: 'Milano Olona',
  },
  {
    id: 'pampanorama2',
    name: 'Panorama Alessandria',
    color: '#0066CC',
    volantino: 'https://www.pampanorama.it/punti-vendita/panorama-alessandria',
    location: 'Alessandria',
  },
  {
    id: 'pampanorama3',
    name: 'Pam Panorama Pino Torinese',
    color: '#0066CC',
    volantino: 'https://www.pampanorama.it/punti-vendita/pino-torinese',
    location: 'Pino Torinese',
  },
  {
    id: 'pamlocal',
    name: 'Pam Local',
    color: '#0066CC',
    volantino: 'https://www.pampanorama.it/punti-vendita/pam-local-roma-botteghe-oscure',
    location: 'Roma - Botteghe Oscure',
  },
  {
    id: 'visotto',
    name: 'Visotto',
    color: '#009640',
    volantino: 'https://www.supermercativisotto.it/volantino',
  },
  {
    id: 'megaprezzibassi',
    name: 'Mega Prezzi Bassi',
    color: '#FFD700',
    volantino: 'https://www.megaprezzibassi.it/stores/mega-pordenone',
    location: 'Pordenone',
  },
  {
    id: 'pewex',
    name: 'Pewex',
    color: '#E30613',
    volantino: 'https://www.pewex-supermercati.it/promozioni/volantini.html',
  },
  {
    id: 'migross1',
    name: 'Migross Superstore',
    color: '#0066CC',
    volantino: 'https://www.migross.it/punti-vendita/superstore-bozzolo/promozioni',
    location: 'Bozzolo',
  },
  {
    id: 'prixquality',
    name: 'Prix Quality',
    color: '#009640',
    volantino: 'https://www.prixquality.com/punti-vendita/pergine-550',
    location: 'Pergine',
  },
  {
    id: 'migross2',
    name: 'Migross Supermarket',
    color: '#0066CC',
    volantino: 'https://www.migross.it/punti-vendita/supermarket-grezzana/promozioni',
    location: 'Grezzana',
  },
  {
    id: 'basko',
    name: 'Basko',
    color: '#009640',
    volantino: 'https://www.basko.it/volantino-offerte/',
  },
  {
    id: 'iperal',
    name: 'Iperal',
    color: '#0066CC',
    volantino: 'https://www.iperal.it/promozioni/',
  },
  {
    id: 'aldi',
    name: 'Aldi',
    color: '#0050AA',
    volantino: 'https://www.aldi.it/it/volantino-online.html',
  },
  {
    id: 'ali',
    name: 'Alì',
    color: '#E30613',
    volantino: 'https://www.alisupermercati.it/negozi-e-volantini/volantini/1338319',
  },
];
